### ISSUE TITLE
MagiskState

### ISSUE THREAD

**Issue by yzkpqv68745** [diareuse/Magisk#4]
If magisk installed(`magiskVersionCode>0`) but manager no root access, manager should show other words instead of `Magisk is not installed`.  In the case of multiple users, other users may be confused (when Multi-user Mode is Device Owner Only).  PS: get magiskVersionCode don't need root access.

**Comment by diareuse** [comment]
You won't get root access if other manager is installed hence the MM concludes Magisk is not installed and shows appropriate text.

**Comment by yzkpqv68745** [comment]
why not try this?
```diff
         } else {
             InputStream nonroot = context.getResources().openRawResource(R.raw.nonroot_utils);
             job.add(nonroot);
+            Config.loadMagiskInfo();
         }
 
         job.add("mount_partitions", "get_flags", "run_migrations", "export BOOTMODE=true").exec();
```
`ShellUtils.fastCmd` will auto try `su` or `shell` mod to run cmds, so we can get the magiskVersionCode.
![1](https://user-images.githubusercontent.com/47681178/57077902-c2bb9d80-6d1f-11e9-96eb-cbeb6f449f95.jpg)

**Comment by yzkpqv68745** [comment]
when Multi-user Mode is Device Owner Only, magisk manager run in other user can't get root access, in this case, manager should not show Magisk is not installed

**Comment by diareuse** [comment]
As of now it works as intended, might get reopened with new design though.

**Comment by yzkpqv68745** [comment]
manager will not display as `Magisk is not installed` until you rewrite it...
