### ISSUE TITLE
Hide Magisk Manager

### ISSUE THREAD

**Issue by lucenera** [diareuse/Magisk#6]
![Screenshot_20190513-141204_Magisk Manager](https://user-images.githubusercontent.com/35407790/57620983-93f8bf00-758a-11e9-94e9-b56859b2b217.jpg)
I can't hide Magisk Manager.  I tried to uninstall and reinstall, but it doesn't work.

**Comment by diareuse** [comment]
Known issue; BouncyCastle fails to sign the new apk.
If you're able to fetch us a logcat to see whether other issue occurs, it would be appreciated.

**Comment by lucenera** [comment]
I use the Logcat Reader app.  How can I extrapolate a log that can be useful to you?  I can also use the terminal.  But I don't know how to do it.

**Comment by diareuse** [comment]
Here's how to use logcat in terminal:
https://developer.android.com/studio/command-line/logcat

You'd put `logcat -m 1500 > log.txt` whilst being on /sdcard (user accessible root folder), which gives you last 1500 lines from logcat for an instance.

**Comment by lucenera** [comment]
[log.txt](https://github.com/diareuse/Magisk/files/3173348/log.txt)
I hope it can help you.

**Comment by diareuse** [comment]
Fixed in latest canary.
