### ISSUE TITLE
Manger crash on module info

### ISSUE THREAD

**Issue by lucenera** [diareuse/Magisk#7]
[log.txt](https://github.com/diareuse/Magisk/files/3182645/log.txt)
The Manager crashes if you search for information on the SanFranciso Fonts module.
To reproduce the error: open Magisk, go to the Download section, search for the SanFrancisco Fonts module and click on the module name.  Instead of displaying the window with the readme of the module, the Manager closes unexpectedly.

**Comment by diareuse** [comment]
This is only 5 seconds of logcat, no stacktrace is present

**Comment by lucenera** [comment]
[logcat_05-15-2019_16-04-08.txt](https://github.com/diareuse/Magisk/files/3182865/logcat_05-15-2019_16-04-08.txt)
This is the logcat of the moment when the app crashes.

**Comment by diareuse** [comment]
This will be fixed in new version - already merged to master
