### ISSUE TITLE
Hidden Magisk Manager cannot detect Magisk.

### ISSUE THREAD

**Issue by Tornado15550** [diareuse/Magisk#8]
On a fresh Magisk installation, hiding Magisk Manager repackages Magisk Manager and scrambles the package name as expected, but the new re-packaged Manager app can no longer detect Magisk.

Steps to reproduce:
1) Completely uninstall magisk along with any/all modules. 
2) Install the latest Magisk built from source through TWRP. The regular Magisk Manager appears and Magisk works as intended. 
3) Re-package Magisk Manager
4) Manager re-packages successfully
5) Open the re-packaged Manager. 

Expected Behavior: Magisk should be detected by the re-packaged Manager and function normally. 

Actual Behavior: Re-packaged Manager states Magisk is no longer installed. 

Re-installing the non-repackaged Manager (via APK) detects Magisk once again and works normally.

OS: Android Q Beta 3
Device: Pixel 2 XL
Architecture: arm64

Two screenshots have also been included which showcase:
1) Magisk working normally when not re-packaged:- 
![Screenshot_20190531-024959](https://user-images.githubusercontent.com/5608158/58747098-95980300-8423-11e9-892e-0ba3066fed7f.png)

2) Magisk no longer being detected by the re-packaged Manager:- 
![Screenshot_20190531-025109](https://user-images.githubusercontent.com/5608158/58747105-9e88d480-8423-11e9-8757-208a01bc566d.png)

Logs: attached below:-
[magisk_log_20190531_024222.log](https://github.com/diareuse/Magisk/files/3243666/magisk_log_20190531_024222.log)

**Comment by martyfender** [comment]
I also have the same issue on my Nextbook Ares 8A's, Intel x86, Android 6.0.1 tablets. In addition, global namespace is not being set, inherit is set on this device with the manager hidden and on devices with it not hidden. I had reverted to a build from a couple of days ago, 2019052801 @ianmacd and upgraded from there today without the magisk not installed issue. If I unhide it and rehide it, I get the magisk not installed issue again. Attached magisk.log from todays build 2019060101. 
[magisk.log](https://github.com/diareuse/Magisk/files/3243855/magisk.log)

**Comment by martyfender** [comment]
I also have the same issue on my Nextbook Ares 8A's, Intel x86, Android 6.0.1 tablets. In addition, global namespace is not being set, inherit is set on this device with the manager hidden and on devices with it not hidden. I had reverted to a build from a couple of days ago, 2019052801 @ianmacd and upgraded from there today without the magisk not installed issue. If I unhide it and rehide it, I get the magisk not installed issue again. Attached magisk.log from todays build 2019060101. 
[Uploading magisk.log…]()
[Log_2019-06-01_10-48-32.txt](https://github.com/diareuse/Magisk/files/3243871/Log_2019-06-01_10-48-32.txt)

**Comment by diareuse** [comment]
This is, as far as I can tell, not the app's problem.

The way this works is as follows:
1) App checks for a package name to see if it matches expectations
    - see [here](https://github.com/diareuse/Magisk/blob/development/app/src/main/java/com/topjohnwu/magisk/ui/SplashActivity.kt#L38)
2) Refreshes versions from remote
3) Simply asks Shell whether the app is given root access
    - see [here](https://github.com/diareuse/Magisk/blob/development/app/src/main/java/com/topjohnwu/magisk/ui/home/HomeViewModel.kt#L179)

There's not a huge deal of detection going on so the culprit must be the Magisk itself.

**Comment by Tornado15550** [comment]
Thanks for looking into this. I'll close the issue here, and re-create it on the main Magisk repo.

**Comment by martyfender** [comment]
@diareuse If that were true then why does reverting to an older version of MM only, 2019052801 @ianmacd solve the issue with his later versions of Magisk, released in the last couple of days?
